module.exports = {
  'exchangeDictionary' : {
    'poloniex' : 'poloniex', '폴로' : 'poloniex', '폴로닉스' : 'poloniex',
    'bittrex' : 'bittrex', '비렉' : 'bittrex', '비트렉스' : 'bittrex',
    'bitfinex' : 'bitfinex', '빗파' : 'bitfinex', '빗피' : 'bitfinex', '빗파이넥스' : 'bitfinex', '빗피넥스' : 'bitfinex',
    'liqui' : 'liqui', '리퀴' : 'liqui',
    'coinone' : 'coinone', '코인원' : 'coinone', '고인원' : 'coinone', '띵훈거래소' : 'coinone',
    'korbit' : 'korbit', '코빗' : 'korbit',
    'gdax' : 'gdax', '지덱스' : 'gdax', '코인베이스' : 'gdax',
    'bithumb' : 'bithumb', '빗썸' : 'bithumb', '빗섬' : 'bithumb',
    'coinnest' : 'coinnest', '코인네스트' : 'coinnest', '코네' : 'coinnest',
    'binance' : 'binance', '바이낸스' : 'binance', '바이넨스' : 'binance', '바낸' : 'binance', '바이넌스' : 'binance',
    'upbit' : 'upbit', '업비트' : 'upbit', '업빗' : 'upbit', '도박장' : 'upbit', '강원랜드' : 'upbit', '하우스' : 'upbit'
   },
   'currencyDictionary' : {
      'btc' : 'btc', 'bitcoin' : 'btc', 'Bitcoin' : 'btc', '비트' : 'btc', '비트코인' : 'btc',
      'bch' : 'bch', '비캐' : 'bch', '빗캐' : 'bch', '비트코인캐시' : 'bch', '비트캐시' : 'bch', '비트코인캐쉬' : 'bch', '비트캐쉬' : 'bch',
      'btg' : 'btg', '빗골' : 'btg', '비골' : 'btg', '비트코인골드' : 'btg', '비트골드' : 'btg',
      'dash' : 'dash', '대시' : 'dash', '대쉬' : 'dash',
      'eth' : 'eth', 'ethereum' : 'eth', '이더' : 'eth', '이더리움' : 'eth',
      'zec' : 'zec', '제트캐시' : 'zec', '제트캐쉬' : 'zec', '제캐' : 'zec',
      'xmr' : 'xmr', '모네로' : 'xmr',
      'ltc' : 'ltc', '라코' : 'ltc', '라이트코인' : 'ltc',
      'gno' : 'gno', '지노시스' : 'gno', '노지스' : 'gno',
      'rep' : 'rep', '어거' : 'rep',
      'etc' : 'etc', '이클' : 'etc', '이더리움클래식' : 'etc',
      'lsk' : 'lsk', '리스크' : 'lsk',
      'strat' : 'strat', '스트라티스' : 'strat', '스트라' : 'strat',
      'steem' : 'steem', '스팀' : 'steem',
      'maid' : 'maid', '메이드' : 'maid', '메이드세이프' : 'maid',
      'xrp' : 'xrp', 'ripple' : 'xrp', '리플' : 'xrp', '리또속' : 'xrp',
      'ardr' : 'ardr', '아더' : 'ardr',
      'gnt' : 'gnt', '골렘' : 'gnt',
      'zrx' : 'zrx',
      'xem' : 'xem', 'nem' : 'xem', '넴' : 'xem', '뉴이코' : 'xem', '뉴이코노미무브먼트' : 'xem',
      'bts' : 'bts', '빗쉐어' : 'bts', '비트쉐어' : 'bts', '방탄' : 'bts',
      'str' : 'str', '스텔라' : 'str',
      'xlm' : 'xlm', '루멘' : 'xlm',
      'dgb' : 'dgb', '디지비' : 'dgb', '대구' : 'dgb',
      'sc' : 'sc', '시아' : 'sc', '시아코인' : 'sc',
      'doge' : 'doge', '도지' : 'doge', '개' : 'doge', '도기' : 'doge', '개코인' : 'doge',
      'gbyte' : 'gbyte', '바이트볼' : 'gbyte',
      'mln' : 'mln', '멜론' : 'mln',
      'neo' : 'neo', '네오' : 'neo',
      'qtum' : 'qtum', '퀀텀' : 'qtum', '똥텀' : 'qtum' , '큐텀' : 'qtum', '큐또속' :  'qtum',
      'omg' : 'omg', '오미세고' : 'omg', '오미세고' : 'omg',
      'mco' : 'mco', '모나코' : 'mco',
      'waves' : 'waves', '웨이브' : 'waves', '웨이브즈' : 'waves',
      'mtl' : 'mtl', '메탈' : 'mtl',
      'ark' : 'ark', '아크' : 'ark',
      'kmd' : 'kmd', '코모도' : 'kmd',
      'pay' : 'pay', 'tenx' : 'pay', '페이' : 'pay', '텐엑스' : 'pay',
      'ant' : 'ant', '아라곤' : 'ant',
      'via' : 'via', '비아코인' : 'via', '비아' : 'via',
      'shift' : 'shift', '쉬프트' : 'shift',
      'tkn' : 'tkn', '토큰카드' : 'tkn',
      'adx' : 'adx', '아덱스' : 'adx',
      'edg' : 'edg', '엣지리스' : 'edg', '엣지' : 'edg',
      'trig' : 'trig', 'trigger' : 'trig', '트리그' : 'trig', '트리거' : 'trig',
      'dct' : 'dct', '디센트' : 'dct',
      'cvc' : 'cvc', '시빅' : 'cvc', '씨빅' : 'cvc',
      'rise' : 'rise', '라이즈' : 'rise',
      'meme' : 'meme', '메메틱' : 'meme',
      'bat' : 'bat', '뱃' : 'bat',
      'nxt' : 'nxt', '넥스트' : 'nxt',
      'snt' : 'snt',
      'ada' : 'ada', 'cardano' : 'ada', '아다' : 'ada', '에이다' : 'ada',
      'eos' : 'eos', '이오스' : 'eos', '에오스' : 'eos',
      'iot' : 'iot', '아이오타' : 'iot', 'iota' : 'iot', '이오티' : 'iot',
      'taas' : 'taas', '타스' : 'taas',
      'knc' : 'knc' , '카이버' :  'knc',
      'stx' : 'stx',
      'eng' : 'eng', '에니그마' : 'eng',
      'snm' : 'snm', '솜' : 'snm',
      'dnt' : 'dnt', '디스트릭트' : 'dnt',
      'bt1' : 'bt1', 'bt2' : 'bt2',
      'bcd' : 'bcd', '빗다' : 'bcd', '비트다이아' : 'bcd', "비트코인다이아" : 'bcd',
      'gas' : 'gas', '가스' : 'gas', '네오가스' : 'gas',
      'mco' : 'mco', '모나코' : 'mco',
      'wtc' : 'wtc', '월튼' : 'wtc',
      'knc' : 'knc', '카이버' : 'knc',
      'ink' : 'ink', '잉크' : 'ink',
      'tsl' : 'tsl', '에너고' : 'tsl',
      'tron' : 'tron', '트론' : 'tron', 'trx' : 'trx',
      'bnb' : 'bnb', '바이낸스코인' : 'bnb',
      'rdn' : 'rdn', '라이덴' : 'rdn',
      'gto' : 'gto', '기프토' : 'gto',
      'mth' : 'mth', '모네타' : 'mth',
      'fun' : 'fun', '펀페어' : 'fun',
      'cnd' : 'cnd', '신디' : 'cnd', '신디케이터' : 'cnd',
      'emc2' : 'emc2', '아인' : 'emc2', '아인스타이늄' : 'emc2',
      'snt' : 'snt', '스테이터스' : 'snt', '스테이터스네트워크토큰' : 'snt',
      'sbd' : 'sbd', '스달' : 'sbd', '스팀달러' : 'sbd',
      'storj' : 'storj', '스토리지' : 'storj',
      'grs' : 'grs', '그리스톨' : 'grs', '그리스톨코인' : 'grs',
      'kmd' : 'kmd', '코모도' : 'kmd',
      'tix' : 'tix', '블록틱스' : 'tix',
      'powr' : 'powr', '파워렛져' : 'powr',
      'ardr' : 'ardr', '아더' : 'ardr',
      'tnb' : 'tnb', '타임뉴뱅크' : 'tnb',
      'mer' : 'mer', '머큐리' : 'mer',
      'vtc' : 'vtc', '버트' : 'vtc', '버트코인' : 'vtc',
      'pivx' : 'pivx', '피백스' : 'pivx'
    }
};
